Introduce /usr/share/help directory
OpenIndiana/oi-userland pull request #11162
Opened 2023-02-23 17:20 UTC by klausz65

2023-02-23 17:26 UTC, AndWac commented
This changes obviously more than just the introduction of a new folder constant.

2023-02-23 21:11 UTC, mtelka requested changes

2023-02-23 21:11 UTC, mtelka commented on make-rules/shared-macros.mk
> -USRSHAREMANDIR =	$(USRSHAREDIR)/man
Why this change?  These lines are _not_ sorted alphabetically.

2023-02-23 21:11 UTC, mtelka commented on make-rules/shared-macros.mk
> +PROTOSBINDIR =	$(PROTO_DIR)$(USRDIR)$(SBINDIR)
Huh.  What is this?  Why?

2023-02-23 21:11 UTC, mtelka commented on make-rules/shared-macros.mk
> +USRSHAREHELPDIR =	$(USRSHAREDIR)/help
Why is this new directory needed?

2023-02-23 21:11 UTC, mtelka commented on make-rules/shared-macros.mk
> -PROTOUSRSHAREDOCDIR =	$(PROTO_DIR)/$(USRSHAREDOCDIR)
Why this change?  These lines are _not_ sorted alphabetically.

2023-02-24 07:28 UTC, mtelka commented on make-rules/shared-macros.mk
> -USRSHAREMANDIR =	$(USRSHAREDIR)/man
... they are not sorted and they are not intended to be sorted.

2023-02-24 07:31 UTC, mtelka commented
I suggest to split this PR to two changes: one for sparc settings and the other one for directories.  It looks like you are trying to do two unrelated things in one changeset.  Thanks.

2023-02-24 07:59 UTC, closed without merging

2023-02-24 07:59 UTC, klausz65 commented
Split this PR into several ones.