samqfs: update 5.64.5
OpenIndiana/oi-userland pull request #13500
Opened 2023-08-23 15:01 UTC by cgrzemba

- all userland services now build in 64bit
	- read LTO loadtimeout from drive to support LTO9
	- keep RPC API compatible with OHSM
	- use GCC10 for build
	- add version to kernel modules

2023-08-23 15:30 UTC, mtelka requested changes

2023-08-23 15:30 UTC, mtelka commented on components/openindiana/samqfs/Makefile
> +COMPONENT_BUILD_ARGS = AMD64=yes DEBUG=no MYSQL_VERSION=mariadb/10.3 SAMQFS_VERSION=$(COMPONENT_VERSION)$(BRANCH_VERSION) NO_BUILD_ACSLS=-D_NoACSLS_
Could you please rebuild this with mariadb 10.6?  Thank you.

2023-08-23 15:32 UTC, mtelka commented on components/openindiana/samqfs/Makefile
> +COMPONENT_BUILD_ARGS = AMD64=yes DEBUG=no MYSQL_VERSION=mariadb/10.3 SAMQFS_VERSION=$(COMPONENT_VERSION)$(BRANCH_VERSION) NO_BUILD_ACSLS=-D_NoACSLS_
With a bit of luck `MYSQL_VERSION=$(MYSQL_IMPLEM)/$(MYSQL_VERSION)` should work, I think.

2023-08-24 06:46 UTC, cgrzemba commented on components/openindiana/samqfs/Makefile
> +COMPONENT_BUILD_ARGS = AMD64=yes DEBUG=no MYSQL_VERSION=mariadb/10.3 SAMQFS_VERSION=$(COMPONENT_VERSION)$(BRANCH_VERSION) NO_BUILD_ACSLS=-D_NoACSLS_
works, Thanks!

2023-08-24 06:48 UTC, cgrzemba commented
works, Thanks!

2023-08-24 06:49 UTC, merged