X 201610 Part 5
OpenIndiana/oi-userland pull request #2450
Opened 2016-10-02 00:36 UTC by alarcher

2016-11-09 14:09 UTC, alarcher commented
@pyhalov Since you already bumped nvidia , should we merge this PR without glamor or wait until Ken provides his fix?

2016-11-09 18:05 UTC, pyhalov commented
if you think that it's fine

2016-12-15 22:55 UTC, pyhalov commented
@alarcher What's the current status of this PR? What was/is wrong with glamor (sorry, don't remember)?

2016-12-15 23:52 UTC, alarcher commented
@pyhalov Requires patching one line in glamor but Ken did not send it. We can remove glamor for now and merge libvdpau. Tell me if I should change anything in the libvdpau commits. I will remove my Nvidia bump from the PR.

2016-12-16 07:10 UTC, pyhalov commented
Why do we need glamor? What are known consumers?

2016-12-16 11:25 UTC, alarcher commented
@pyhalov xorg-video-ati and xorg-video-intel can use it to accelerate 2D rendering.

2016-12-17 07:18 UTC, pyhalov commented
Note, that if you integrate it before https://github.com/OpenIndiana/oi-userland/pull/2669 , we can remove ffmpeg dependency on nvidia

2016-12-17 07:19 UTC, pyhalov commented
BTW, can we remove nvidia's vdpau and leave only this one? Are they compatible?

2016-12-18 21:00 UTC, tomww commented
Nvidia writes in a release doc that vdpau will be removed from the driver package.
While this version looks like still including the  wrapper library:
http://us.download.nvidia.com/solaris/352.79/README/vdpausupport.html
Then this version writes aout the external available wrapper library:
http://us.download.nvidia.com/solaris/375.26/README/vdpausupport.html
(not necessarily at the version in the URL above removed the vdpau wrapper lib)

Which version of the Nvidia driver will be in the repo? Depending on this version we need the external wrapper library jumping in.

If OI should include an older driver with the wrapper, then it could be an idea to remove vdpau files from the OI delivered nvidia package at the time when the new vdpau wrapper goes in. Including a new required dependency in nvida driver would be necessary.
If users install their own copy of the nvidia driver (some need to for older Chips), then they would need to install the OI -vdpau package on their own. I would not make a dependency in the consuming packages like vlc.

2016-12-19 16:23 UTC, alarcher commented
@pyhalov @tomww As a first step we should keep libvdpau with 34x drivers and mediate the symlinks in the common directories. The NVIDIA libraries do not bother anyone as they live in their own directory, only the symlinks are to blame.
The new libvdpau is already installed in another prefix together with other Xorg libs.
We already discussed that we want to leave the possibility to install 34x even after 36x because fairly common Quadro adapters are not supported by 36x

2016-12-19 20:39 UTC, pyhalov requested changes

2016-12-19 20:39 UTC, pyhalov commented on components/openindiana/nvidia/driver-graphics-nvidia.p5m
> -link path=usr/include/vdpau target=../X11/include/NVIDIA/vdpau
Please, bump COMPONENT_REVISION for nvidia  component

2016-12-19 20:39 UTC, pyhalov commented on components/x11/libvdpau/Makefile
> +
REQUIRED_PACKAGES?

2016-12-19 20:42 UTC, pyhalov commented
You spoke about mediated symlinks. Are you going to add them in this PR or later?

2016-12-20 10:04 UTC, alarcher commented
I am working on the links for this PR to be able to merge before the ffmpeg PR as you suggested earlier.

2017-01-10 18:28 UTC, pyhalov commented
@alarcher : what's the current status of this PR?

2017-01-16 14:04 UTC, pyhalov commented on components/x11/libvdpau/manifests/sample-manifest.p5m
> +file path=usr/etc/vdpau_wrapper.cfg
usr/etc/ ? Is something misconfigured?

2017-01-18 09:38 UTC, pyhalov commented
Superseeded by https://github.com/OpenIndiana/oi-userland/pull/2732

2017-01-18 09:38 UTC, closed without merging