Sg3 utils bump to 1.42
OpenIndiana/oi-userland pull request #2494
Opened 2016-10-15 07:04 UTC by grueni

2016-10-15 08:55 UTC, AndWac requested changes
1. Move to appropriate category (eg. sysutils)
2. Make use of $(WS_MAKE_RULES) in Makefile
3. Add REQUIRED_PACKAGES to Makefile

2016-10-15 14:35 UTC, AndWac requested changes
This package needs also a new home. As it's also a system package I propose to move it into components/sysutils.
And then squash the commits when finished.

2016-10-15 17:30 UTC, alarcher commented on components/sg3_utils/Makefile
> +CFLAGS += -D__EXTENSIONS__ -D_XOPEN_SOURCE=1 -D_XOPEN_SOURCE_EXTENDED=1
Just to make sure that you really want compliance with XPG4v2, right?

2016-10-15 17:31 UTC, alarcher commented on components/sg3_utils/Makefile
> +include $(WS_MAKE_RULES)/depend.mk
You can remove lines 75 and 77.

2016-10-15 17:31 UTC, alarcher commented on components/sg3_utils/Makefile
> +COMPONENT_LICENSE_FILE= $(COMPONENT_NAME).license
You can remove line 39, it is enforced by default.

2016-10-15 17:33 UTC, alarcher commented on components/sg3_utils/sg3_utils.p5m
>  <transform file path=usr.*/man/.+ -> default mangler.man.stability uncommitted>
I think this transform is applied by default and can be removed.

2016-10-15 17:34 UTC, alarcher commented on components/sg3_utils/sg3_utils.p5m
>  depend type=optional fmri=consolidation/desktop/desktop-incorporation@5.12-5.12.0.0.0.4.0
Not sure that this dependency still makes sense.

2016-10-17 09:17 UTC, xen0l approved these changes

2016-10-17 09:22 UTC, xen0l commented
I'm fine with the changes and will be merging shortly. Thanks @grueni for the change, @AndWac and @alarcher for reviewing.

2016-10-17 09:26 UTC, pyhalov commented on components/sysutils/sg3_utils/Makefile
> +EQUIRED_PACKAGES += system/library
REQUIRED_PACKAGES, not EQUIRED_PACKAGES

2016-10-17 10:43 UTC, xen0l commented
Continuted in #2499

2016-10-17 10:43 UTC, closed without merging