smartmoontools bump to 6.5
OpenIndiana/oi-userland pull request #2495
Opened 2016-10-15 07:05 UTC by grueni

2016-10-15 08:48 UTC, AndWac requested changes
1. Please move smartmontools to an appropriate category folder, eg. sysutils
2. Make use of $(WS_MAKE_RULES) for prep.mk, configure.mk and ips.mk in Makefile
3. Add REQUIRED_PACKAGES to Makefile

2016-10-15 14:32 UTC, AndWac requested changes
You still need to move the whole package into a component sub-folder, eg. components/sysutils.
We started to organize the packages some week ago.
Furthermore, when done you should squash the commits into a single one.

2016-10-15 17:35 UTC, alarcher commented on components/smartmontools/Makefile
> +COMPONENT_LICENSE_FILE= $(COMPONENT_NAME).license
COMPONENT_LICENSE_FILE can be removed.

2016-10-15 17:36 UTC, alarcher commented on components/smartmontools/Makefile
>  COMPONENT_PRE_CONFIGURE_ACTION = \
Put COMPONENT_PRE_CONFIGURE_ACTION after the includes.

2016-10-15 17:40 UTC, alarcher commented on components/smartmontools/Makefile
> +test:		$(NO_TEST)
Why disable the tests? Also the macros is NO_TESTS.

2016-10-15 17:40 UTC, alarcher commented on components/smartmontools/Makefile
> +include $(WS_MAKE_RULES)/depend.mk
Line 59 can be removed.

2016-10-15 17:42 UTC, alarcher commented on components/smartmontools/smartmontools.p5m
> +file path=etc/smartd_warning.sh
Is this shell script really supposed to be in /etc? Also if it is to be executed you need to append mode=0555

2016-10-17 09:18 UTC, xen0l approved these changes

2016-10-17 09:22 UTC, xen0l commented
I'm fine with the changes and will be merging shortly. Thanks @grueni for the change, @AndWac and @alarcher for reviewing.

2016-10-17 10:28 UTC, merged