EOF areca
OpenIndiana/oi-userland pull request #2508
Opened 2016-10-18 15:22 UTC by xen0l

2016-10-18 15:24 UTC, alarcher approved these changes

2016-10-18 15:44 UTC, pyhalov requested changes
Please, properly mark it obsolete

2016-10-18 16:18 UTC, pyhalov commented on components/meta-packages/history/history
> +backup/areca@7.1-2013.0.0.0
backup/areca@7.11,5.11-2016.0.1.0

2016-10-18 16:19 UTC, pyhalov commented on components/meta-packages/history/history
> +backup/areca@7.1-2013.0.0.0
Just to avoid confusion with other 2013.x packages

2016-10-18 19:47 UTC, pyhalov commented on components/meta-packages/history/history
> +library/idnkit
you need precise versions

2016-10-19 16:48 UTC, pyhalov commented on components/meta-packages/history/history
> +backup/areca@7.1,5.11-2016.0.1.0
sorry, but this file is sorted :)

2016-10-19 17:33 UTC, pyhalov commented
You forgot to remove areca from components.ignore :)

2016-10-19 17:37 UTC, merged