Add corosync, pacemaker, service-hacluster
OpenIndiana/oi-userland pull request #2543
Opened 2016-10-27 17:59 UTC by grueni

Update corosync, add pacemaker and service-hacluster

2016-10-27 18:36 UTC, alarcher commented on components/cluster/corosync/corosync.p5m
> +file path=usr/lib/libcfg.a
Static libs to be removed.

2016-10-28 05:23 UTC, pyhalov commented on components/cluster/corosync/Makefile
> +  echo "}"  >> ${PROTO_DIR}/etc/corosync/uidgid.d/uid.conf  )
Perhaps, better just deliver files/uid.conf use something like 'file files/uid.conf path='blah'...' in manifest?

2016-10-28 18:23 UTC, xen0l requested changes

2016-10-28 18:23 UTC, xen0l commented on components/cluster/corosync/Makefile
> +CONFIGURE_OPTIONS += --sharedstatedir=/var/cluster
/var/cluster vs /var/run/hacluster (different values), we should possibly unite this.

2016-10-28 18:23 UTC, xen0l commented on components/cluster/corosync/corosync.p5m
> +file path=etc/logrotate.d/corosync
Remove this line. We could ship logadm entry in /etc/logadm.d instead. We can ship this file in /usr/share/examples/corosync

2016-10-28 18:23 UTC, xen0l commented on components/cluster/corosync/corosync.p5m
> +file path=etc/corosync/corosync.conf.example
We should ship example files under /usr/share/examples/corosync instead of /etc.

2016-10-28 18:23 UTC, xen0l commented on components/cluster/pacemaker/Makefile
> +CONFIGURE_OPTIONS += --sharedstatedir=/var/cluster
/var/cluster vs /var/hacluster unity

2016-10-28 18:23 UTC, xen0l commented on components/cluster/pacemaker/Makefile
> +REQUIRED_PACKAGES += runtime/perl-516
We should stick to using runtime/perl-522 instead of runtime/perl-516

2016-10-28 18:23 UTC, xen0l commented on components/cluster/service-hacluster/Makefile
> +PKG_PROTO_DIRS += $(COMPONENT_DIR)/files
You can remove this and use files/... p5m manifest file.

2016-10-28 18:23 UTC, xen0l commented on components/cluster/service-hacluster/files/svc-hacluster
> +	sleep $SLEEPINTERVALL
Please unite ${FOO} vs $FOO

2016-10-28 18:23 UTC, xen0l commented on components/cluster/service-hacluster/service-hacluster.license
> +TBD
We need license here.

2016-10-28 18:23 UTC, xen0l commented on components/cluster/service-hacluster/service-hacluster.p5m
> +file hacluster.xml path=lib/svc/manifest/application/hacluster.xml restart_fmri=svc:/system/manifest-import:default
Use full relative path to Makefile like in other components.

2016-10-28 18:26 UTC, xen0l requested changes
In pacemaker.p5m (just too big to display):
- ship logrotate file in /usr/share/examples/pacemaker
- split tests into separate package
- what about man pages? Section 8 vs 1M

2016-11-09 14:57 UTC, xen0l approved these changes

2016-11-09 14:58 UTC, xen0l commented
To be merged after https://github.com/OpenIndiana/oi-userland/pull/2542.

2016-11-10 14:30 UTC, xen0l commented
This change has been marked for inclusion. Please, squash commits.

2016-11-18 17:55 UTC, merged