Initial commit of sysstat version 20151012
OpenIndiana/oi-userland pull request #2564
Opened 2016-10-30 13:56 UTC by jimklimov

Another useful tool from the author of mbuffer

2016-10-30 20:46 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +#
As always, category better to correspond to fmri

2016-10-30 20:47 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +# non-autoconf "configure" script here
perhaps, use configure.mk and CONFIGURE_OPTIONS =  (I mean, completely overwrite them?)

2016-10-31 00:58 UTC, jimklimov commented on components/sysutils/sysstat/Makefile
> +# non-autoconf "configure" script here
Not sure it makes sense here to pretend that the script is compatible to autoconf configure (as other parts of that makefile can assume now or later) when it is an arbitrary script with the same name. As for FMRI - this and xjobs recipes were copied from mbuffer which got into this classification :)

2016-11-01 20:23 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +# non-autoconf "configure" script here
@xen0l - what do you think about it? I still feel inconvenient about this PRE_BUILD_ACTION. 
Also, as script doesn't use configure.mk, COMPONENT_PRE_CONFIGURE_ACTION is not used.

2016-11-01 20:39 UTC, xen0l commented
We should either deliver SMF manifest for sysstatd or drop it for now. Also, separating these into two packages would be good.

2016-11-01 20:43 UTC, xen0l commented
Also, please drop mbuffer changes.

2016-11-01 20:46 UTC, xen0l requested changes

2016-11-01 20:46 UTC, xen0l commented on components/shell/sysstat/Makefile
> +COMPONENT_FMRI=		shell/sysstat
shell/sysstat -> diagnostic/sysstat, also ship it in sysutils/

2016-11-01 20:46 UTC, xen0l commented on components/shell/sysstat/sysstat.p5m
> +file path=usr/sbin/$(MACH64)/sysstatd
Separate sysstatd into separate package. I expect people will use sysstat alone.

2016-11-01 20:46 UTC, xen0l commented on components/shell/sysstat/sysstat.p5m
> +file path=usr/sbin/$(MACH32)/sysstatd
No manpage for sysstatd?

2016-11-01 21:09 UTC, jimklimov commented on components/shell/sysstat/sysstat.p5m
> +file path=usr/sbin/$(MACH32)/sysstatd
None, and few mentions in the docs. Source file and content (somewhat) is different, though.

2016-11-01 21:10 UTC, jimklimov commented on components/shell/sysstat/sysstat.p5m
> +file path=usr/sbin/$(MACH64)/sysstatd
It seems (from readme) that `sysstat -d` provides similar functionality. But ok, separated if you like so.

2016-11-01 21:10 UTC, jimklimov commented on components/shell/sysstat/Makefile
> +COMPONENT_FMRI=		shell/sysstat
done

2016-11-01 21:12 UTC, jimklimov commented
> We should either deliver SMF manifest for sysstatd or drop it for now. Also, separating these into two packages would be good.

You did not read the PR header, did you? Or chose to ignore it? TL;DR version is: you want a feature - merge the foundation and vote with your PRs on top - this gets around faster ;)

2016-11-04 11:33 UTC, jimklimov commented
@xen0l : So... how is the latest PR version?

Most of your comments were addressed, except for an SMF service. I am not ready now to look at what it requires to run and how to do it securely, so would rather leave the exercise for somebody who would be first (next) to use this to monitor several OI/Hipster installations from one console ;)

2016-11-09 15:10 UTC, xen0l commented
I am fine with the changes, but I don't like shipping a service package without SMF manifest. @pyhalov your bet on this?

2016-11-09 18:11 UTC, pyhalov commented
If we deliver daemon which can be usable in any way, we should provide SMF manifest.

2016-11-09 18:43 UTC, jimklimov commented
At this time I'm not responsibly ready to wrap the service - I am not
certain what it does, what rights it needs and what insecurities it brings
- or carefully does not and so successfully avoids.

We can deliver just the daemon binary, so that somebody else who ever (if
ever) needs this feature, researches and SMFizes it correctly for their
system, and upstreams the change to us. We can also drop delivering the
daemon and stiffle innovation in this area ;)

If you already have a strong opinion about how this should be SMFized -
feel free to merge the PR with code+recipe and follow up with your PR with
a manifest shortly.

2016-11-09 19:11 GMT+01:00 Alexander Pyhalov <notifications@github.com>:

> If we deliver daemon which can be usable in any way, we should provide SMF
> manifest.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenIndiana/oi-userland/pull/2564#issuecomment-259483445>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABj5lMyq4Pg7572gjFoSfDDTLduHLTqNks5q8gzYgaJpZM4KkYZN>
> .
>

2016-11-10 14:25 UTC, xen0l commented
I don't have time for investigating SMF service right now. Would you be able to provide even basic SMF service? RBAC integration is just an added value in many cases.

2016-11-10 22:32 UTC, jimklimov commented
Some manifest added (untested) :)

2016-11-10 23:07 UTC, xen0l commented
What does svccfg validate say? Can you at least run the service and application works?

2016-12-07 12:52 UTC, pyhalov commented
Did you check service? Can you update Makefile to use configure.mk?

2016-12-07 16:20 UTC, jimklimov commented on components/sysutils/sysstat/Makefile
> +# non-autoconf "configure" script here
Thanks, good catch with this one - removed the action with no losses :)

2016-12-07 16:50 UTC, jimklimov commented
Ok, so I experimented with this a bit.

1) The daemon is required in any case - if a service is not running, the client launches it as a sub-process to monitor the local machine, using the same multicast strategy (by default)

2) If the daemon is started manually, or via SMF, the client connects to it
2.1) If I then kill the daemon, client stops refreshing

3) not checked - the client should be able to track a farm reported by sysstatd's on each node.

2016-12-07 18:48 UTC, pyhalov commented on components/sysutils/sysstat/sysstat.p5m
> +license $(COMPONENT_LICENSE_FILE) license='$(COMPONENT_LICENSE)'
Remove second license action

2016-12-07 18:50 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +COMPONENT_PRE_BUILD_ACTION = \
Please, convert it to using configure.mk, like nginx.

2016-12-08 09:55 UTC, jimklimov commented on components/sysutils/sysstat/Makefile
> +COMPONENT_PRE_BUILD_ACTION = \
It is NOT using autoconf configure. So IMHO the recipe integration for configure.mk is a poor choice here. We have many recipes for projects with justmake.mk, including projects who poorly chose the name for their build-setup scripts "configure" without following the autoconf CLI-API.

Of course, anything can be twisted into anything else (e.g. by overriding proper autoconfigure with pieces for this custom one), but I assume it is a dark path to follow ;)

Conversely: is there something that does not work up to spec with recipe as is? Is there a practical reason to twist it?

2016-12-08 10:12 UTC, jimklimov commented on components/sysutils/sysstat/Makefile
> +#
Perhaps, but

1) There is no "diagnostic/" directory
2) There are many packages with "diagnostic/" FMRI, mostly sniffers and local load analyzers
3) The closest equivalent to sysstat is "diagnostic/top" which is why I picked this FMRI patern

2016-12-08 10:50 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +#
I'm fine with this category

2016-12-08 10:59 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +COMPONENT_PRE_BUILD_ACTION = \
@xenol: Are you OK with it?

2016-12-08 19:55 UTC, xen0l commented on components/sysutils/sysstat/Makefile
> +COMPONENT_PRE_BUILD_ACTION = \
@pyhalov yes. @jimklimov thanks for providing the testing results.

2016-12-08 19:55 UTC, xen0l approved these changes

2016-12-08 19:56 UTC, xen0l commented
This change has been marked for inclusion. Please, squash commits.

2016-12-08 19:59 UTC, jimklimov commented
Thanks. Tomorrow, i guess.

--
Typos courtesy of GMail on my Samsung Android

08.12.2016 20:56 пользователь "Adam Števko" <notifications@github.com>
написал:

> This change has been marked for inclusion. Please, squash commits.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenIndiana/oi-userland/pull/2564#issuecomment-265838532>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABj5lIOEiPemenqVr_sely1oYQ16HN0dks5rGGDhgaJpZM4KkYZN>
> .
>

2016-12-08 20:15 UTC, pyhalov commented on components/sysutils/sysstat/Makefile
> +COMPONENT_PRE_BUILD_ACTION = \
Perhaps, at least split it in several (2?) lines to fit in 80 lines?

2016-12-09 08:13 UTC, jimklimov commented
Squashed

2016-12-09 09:53 UTC, merged