Initial commit of vpnc version 0.5.3
OpenIndiana/oi-userland pull request #2607
Opened 2016-11-17 22:10 UTC by jimklimov

The IPsec capable VPN client. Or so it claims in multiple OSes ;)

2016-11-17 22:27 UTC, xen0l requested changes

2016-11-17 22:27 UTC, xen0l commented on components/network/vpnc/vpnc.p5m
> +file etc/vpnc/default.conf path=etc/vpnc/default.conf.example
Please, ship example file in /usr/share/examples/vpnc

2016-11-17 22:27 UTC, xen0l commented on components/network/vpnc/vpnc.p5m
> +file path=usr/bin/$(MACH64)/cisco-decrypt
Do we need 64bit bins here?

2016-11-17 22:38 UTC, xen0l approved these changes

2016-11-17 22:55 UTC, jimklimov commented on components/network/vpnc/vpnc.p5m
> +file path=usr/bin/$(MACH64)/cisco-decrypt
per IRC, this is preparation for the 64-bitness of the OS, and the Makefile needed some coercing to do the 64-bit builds/installs into correct paths, so I'd rather keep it (to not redo it later)

2016-11-18 17:52 UTC, xen0l commented
This change has been marked for inclusion. Please, squash commits.

2016-11-19 17:59 UTC, jimklimov commented
Squashed

2016-11-23 21:28 UTC, xen0l commented
Squash commits

2016-11-24 00:06 UTC, jimklimov commented
Squeak!.. Whoosh!...

2016-11-24 04:44 UTC, merged