Bump cirrus driver and set default depth to 16 bpp
OpenIndiana/oi-userland pull request #2794
Opened 2017-02-16 21:23 UTC by Mno-hime

Current xf86-video-cirrus X11 driver does not work with Qemu emulated
GD5446 graphics adapter (on Linux Qemu v2.6.2 at least) - opening
terminal results in distorted, visally unstable window.

This is now fixed with setting default depth to 16 bpp (was 24 bpp).

Also the driver was bumped to version 1.5.3 and `NoAccel` set as a
default. All changes are from upstream. Two OpenIndiana-specific
patches were updated.

Tested with current OpenIndiana on Linux Qemu KVM v2.8.0 with `-vga
cirrus`.

2017-02-16 21:27 UTC, Mno-hime commented
@alarcher FYI.

2017-02-16 21:37 UTC, alarcher approved these changes

2017-02-16 21:37 UTC, alarcher commented on components/x11/xf86-video-cirrus/Makefile
>  COMPONENT_REVISION=1
You can remove COMPONENT_REVISION as the COMPONENT_VERSION was bumped.

2017-02-16 21:39 UTC, alarcher commented on components/x11/xf86-video-cirrus/Makefile
>  COMPONENT_REVISION=1
Stupid page just shifted when I clicked, so just fix the component revision and it should be fine.

2017-02-16 21:40 UTC, alarcher requested changes
Just remove COMPONENT_REVISION and this is good.

2017-02-17 17:32 UTC, Mno-hime commented
`COMPONENT_REVISION` removed.

2017-02-17 18:48 UTC, alarcher approved these changes

2017-02-17 18:49 UTC, alarcher commented
@Mno-hime Thanks. Compiled and published locally.

2017-02-17 21:43 UTC, merged