Bump valgrind to 3.12.0
OpenIndiana/oi-userland pull request #2929
Opened 2017-03-29 02:12 UTC by alarcher

2017-03-29 08:59 UTC, xen0l approved these changes

2017-03-29 10:13 UTC, pyhalov commented
gmake test fails to compile tests:
```
valgrind-3.12.0/memcheck/tests/badjump2.c:21:21: error: storage size of ‘sigsegv_new’ isn’t know
...
```

2017-03-30 20:30 UTC, alarcher commented
Fixed with -D__EXTENSIONS__ but other issues related to asm. I do not know this type of things (yet).

2017-04-05 02:40 UTC, alarcher commented
Fixed with -std=gnu99 for asm only defined as GNU extension.

2017-04-05 07:50 UTC, pyhalov requested changes

2017-04-05 07:50 UTC, pyhalov commented on components/developer/valgrind/valgrind.p5m
> +file path=usr/include/valgrind/config.h
Comment on upper part of valgrind.p5m : what is the point of having isaexec symlinks an delivering only 64-bit version? I'd dropped them and delivered just 64-bit binaries in /usr/bin . 'CONFIGURE_BINDIR.64 = $(CONFIGURE_PREFIX)/bin' can help.

2017-04-05 08:35 UTC, alarcher commented
Just dates back to the time when we did not authorize 64bit in /usr/bin. Should be OK now.

2017-04-05 08:39 UTC, pyhalov commented on components/developer/valgrind/Makefile
>  include $(WS_TOP)/make-rules/prep.mk
Sorry.. Please, switch to $(WS_MAKE_RULES) :)

2017-04-05 08:50 UTC, alarcher commented
Done.

2017-04-05 08:54 UTC, pyhalov approved these changes

2017-04-05 08:55 UTC, merged