exiv2: add to oi-userland
OpenIndiana/oi-userland pull request #2962
Opened 2017-04-06 14:35 UTC by cgrzemba

Please add to oi-userland, with exiv2 gthumb is able to handle exif data of pictures.
but check if the subdirectory 'library' the right place for the recipe, for me it is a library but it ships also a CLI command

2017-04-06 19:01 UTC, pyhalov commented on components/library/exiv2/Makefile
> +LDFLAGS += -m$(BITS) -lnsl -lsocket
We have LDFLAGS =$(LD_BITS) by default. Why is it needed to add -m$(BITS)?

2017-04-06 19:02 UTC, pyhalov commented on components/library/exiv2/Makefile
> +include $(WS_TOP)/make-rules/prep.mk
Please, switch to $(WS_MAKE_RULES)

2017-04-06 19:02 UTC, xen0l requested changes
Library category is fine by me. What abotu REQURIED_PACKAGES? Aparat from these comment reviews, LGTM.

2017-04-06 19:02 UTC, xen0l commented on components/library/exiv2/Makefile
> +include $(WS_TOP)/make-rules/prep.mk
$(WS_TOP)/make-rules -> $(WS_MAKE_RULES)

2017-04-06 19:02 UTC, xen0l commented on components/library/exiv2/exiv2.p5m
> +file path=usr/include/exiv2/config.h
You are compiling both 32bit and 64bit. Are the headers the same?

2017-04-06 19:03 UTC, pyhalov commented on components/library/exiv2/Makefile
> +COMPONENT_BUILD_ARGS += PATH="/usr/gnu/bin:$(PATH)"
Perhaps, better do it on top level? Just set 
PATH=$(PATH.gnu)
in the beginning (somewhere around 37 line).

2017-04-06 19:04 UTC, pyhalov commented on components/library/exiv2/Makefile
> +install: $(INSTALL_32_and_64)
Add test target (at least with $(NO_TESTS), but if library has some tests, better to use them).

2017-04-06 19:05 UTC, pyhalov commented on components/library/exiv2/exiv2.p5m
> +file path=usr/bin/exiv2
Why deliver both? Perhaps, just deliver 64-bit copy in /usr/bin?

2017-04-06 19:07 UTC, pyhalov commented on components/library/exiv2/exiv2.p5m
> +file path=usr/include/exiv2/bmpimage.hpp
Have you compared include files, delivered by 32 and 64 bits build? If they are different, this should be accounted for (for example as it's done in python - look at https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/python/python27/Makefile#L102 an component's manifest.

2017-04-06 19:08 UTC, pyhalov commented on components/library/exiv2/Makefile
> +install: $(INSTALL_32_and_64)
Also component misses REQUIRED_PACKAGES

2017-04-07 06:04 UTC, cgrzemba commented on components/library/exiv2/Makefile
> +LDFLAGS += -m$(BITS) -lnsl -lsocket
no idea, on linking with g++ it is missing

2017-04-07 06:32 UTC, cgrzemba commented on components/library/exiv2/Makefile
> +COMPONENT_BUILD_ARGS += PATH="/usr/gnu/bin:$(PATH)"
This construct exists nowhere, but I can set 
PATH:=$(GNUBIN):$(PATH)

2017-04-07 06:33 UTC, cgrzemba commented on components/library/exiv2/exiv2.p5m
> +file path=usr/bin/exiv2
do we have something like INSTALL_64_LIBS_ONLY?

2017-04-07 06:53 UTC, cgrzemba commented on components/library/exiv2/exiv2.p5m
> +file path=usr/include/exiv2/config.h
The headers are all the same

2017-04-07 06:57 UTC, cgrzemba commented on components/library/exiv2/exiv2.p5m
> +file path=usr/bin/exiv2
or BUILD_32_LIBS_ONLY

2017-04-07 15:55 UTC, pyhalov commented on components/library/exiv2/Makefile
> +LDFLAGS += -m$(BITS) -lnsl -lsocket
I've removed it and it still works

2017-04-07 15:58 UTC, pyhalov commented on components/library/exiv2/Makefile
> +test: $(TEST_32_and_64)
1) style - test target follows install target
2) gmake test fails (as exiv2 doesn't support check target), so  change it to test: $(NO_TESTS)

2017-04-11 09:37 UTC, cgrzemba commented
Done.

2017-04-11 12:34 UTC, pyhalov requested changes

2017-04-11 12:34 UTC, pyhalov commented on components/library/exiv2/Makefile
> +PATH:=$(GNUBIN):$(PATH)
One small issue: in spite of recent @jgmills changes you can use just 'PATH=$(PATH.gnu)'

2017-04-11 13:14 UTC, pyhalov commented
ehm? Why does this PR contain > 250 commits?

2017-04-11 13:16 UTC, closed without merging

2017-04-11 13:18 UTC, cgrzemba commented
I fight against the rebase nightmare

2017-04-11 13:25 UTC, alarcher commented
If you git pull --rebase origin oi/hipster there should not be any issue.