vala: move to category runtime and adapt Makefile and manifest
OpenIndiana/oi-userland pull request #2992
Opened 2017-04-17 19:47 UTC by AndWac

I have changed the COMPONENT_FMRI from developer/vala to runtime/vala and removed the superfluous COMPONENT_DESCRIPTION (copy of COMPONENT_SUMMARY).

2017-04-17 21:17 UTC, alarcher commented
You need to add a history file to trigger the rename, see https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/developer/clang-38/history

2017-04-17 21:21 UTC, alarcher requested changes
History file required.

2017-04-17 21:21 UTC, alarcher commented on components/runtime/vala/Makefile
> +COMPONENT_LICENSE_FILE=	vala.license
You can remove COMPONENT_LICENSE_FILE.

2017-04-17 21:21 UTC, alarcher commented on components/runtime/vala/Makefile
> +REQUIRED_PACKAGES += SUNWcs
Are there build dependencies that are not auto-generated? (e.g. header-only packages)

2017-04-17 21:21 UTC, alarcher commented on components/runtime/vala/vala.p5m
>  <transform file path=usr.*/man/.+ -> default mangler.man.stability uncommitted>
I think this one is now a default transform.

2017-04-18 05:05 UTC, pyhalov commented on components/runtime/vala/Makefile
> +COMPONENT_FMRI=		runtime/vala
Please, don't change FMRI without really good reason

2017-04-18 16:44 UTC, AndWac commented on components/runtime/vala/Makefile
> +REQUIRED_PACKAGES += SUNWcs
I had checked this (following your receipt): dependencies detected via grep in configure.ac are glib-2.0, gobject-2.0, gmodule-2.0 and gthread-2.0.
I concluded that I don't have to add other dependencies than the generated.

2017-04-18 16:46 UTC, AndWac commented on components/runtime/vala/vala.p5m
>  <transform file path=usr.*/man/.+ -> default mangler.man.stability uncommitted>
Ok, seems you are right. I've found
defaults:<transform file path=usr.*/man/.+ -> default mangler.man.stability uncommitted>
in the transformations folder.

2017-04-18 16:48 UTC, AndWac commented on components/runtime/vala/Makefile
> +COMPONENT_FMRI=		runtime/vala
Ok, I can revert this. I thought it was a good idea because I moved vala to the runtime folder. Maybe I should move it to developer?

2017-04-18 16:56 UTC, alarcher commented on components/runtime/vala/Makefile
> +REQUIRED_PACKAGES += SUNWcs
Great, thank you.

2017-04-18 16:56 UTC, alarcher commented on components/runtime/vala/Makefile
> +COMPONENT_FMRI=		runtime/vala
Yes just move it to developer, as long as it is consistent it is fine.

2017-04-18 18:40 UTC, alarcher approved these changes

2017-04-18 18:53 UTC, merged