Some GCC 6 fixes
OpenIndiana/oi-userland pull request #3041
Opened 2017-05-03 19:15 UTC by alarcher

2017-05-03 22:51 UTC, xen0l approved these changes

2017-05-03 22:53 UTC, xen0l requested changes

2017-05-03 22:53 UTC, xen0l commented on components/library/libgnomeui/patches/libgnomeui-04-gcc6.patch
> +--- libgnomeui-2.24.5/libgnomeui/gnome-dateedit.c.orig	Fri Apr 28 19:30:02 2017
Patch is added, so we need to bump component revision

2017-05-03 22:53 UTC, xen0l commented on components/library/wxwidgets/patches/01-gcc6.patch
> +
Bump component_revision, so patch is applied.

2017-05-03 23:02 UTC, alarcher commented on components/library/wxwidgets/patches/01-gcc6.patch
> +
Done.

2017-05-03 23:35 UTC, alarcher commented on components/library/libgnomeui/patches/libgnomeui-04-gcc6.patch
> +--- libgnomeui-2.24.5/libgnomeui/gnome-dateedit.c.orig	Fri Apr 28 19:30:02 2017
Done.

2017-05-04 06:11 UTC, pyhalov commented on components/library/libgnomeui/Makefile
> -include ../../make-rules/shared-macros.mk
perhaps it's better to move gnome2 libraries to desktop/gnome2/ ?

2017-05-04 14:32 UTC, alarcher commented on components/library/libgnomeui/Makefile
> -include ../../make-rules/shared-macros.mk
I initially put them in desktop/gnome2 but the category layout specifies library/* to go to library. What do you prefer?

2017-05-04 15:00 UTC, pyhalov commented on components/library/libgnomeui/Makefile
> -include ../../make-rules/shared-macros.mk
do it the same way with mate libs

2017-05-04 16:37 UTC, alarcher commented
Updated.

2017-05-04 17:48 UTC, merged