Add GNU Global source code tagging system.
OpenIndiana/oi-userland pull request #3053
Opened 2017-05-04 22:33 UTC by dsendkowski

2017-05-04 22:45 UTC, alarcher requested changes
Aside from the minor nitpick and adding REQUIRED_PACKAGES, it looks very good.
Thank you!

2017-05-04 22:45 UTC, alarcher commented on components/developer/global/Makefile
> +COMPONENT_SRC=		global-$(COMPONENT_VERSION)
Small nitpick, you can leave $(COMPONENT_NAME) instead of 'global' line 23.

2017-05-04 22:45 UTC, alarcher commented on components/developer/global/Makefile
> +
Run gmake REQUIRED_PACKAGES to add runtime dependencies.
If there are undetected build dependencies, you need to add them manually.

2017-05-04 22:45 UTC, alarcher commented on components/developer/global/Makefile
> +COMPONENT_FMRI=         developer/global
The category and classification are consistent with cscope, it is all good. :)

2017-05-05 07:03 UTC, dsendkowski commented on components/developer/global/Makefile
> +
OK, I've added REQUIRED_PACKAGES returned by `gmake REQUIRED_PACKAGES`.

2017-05-05 07:55 UTC, pyhalov commented on components/developer/global/Makefile
> +
OK, remove empty line in end of Makefile and squash commits.

2017-05-05 08:50 UTC, dsendkowski commented on components/developer/global/Makefile
> +
OK, done.

2017-05-05 10:04 UTC, pyhalov commented on components/developer/global/Makefile
> +
please, squash commits, so that it's only one commit in PR. https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

2017-05-05 11:00 UTC, dsendkowski commented on components/developer/global/Makefile
> +
I guess it is OK now.

2017-05-05 11:44 UTC, pyhalov approved these changes

2017-05-05 11:49 UTC, alarcher approved these changes

2017-05-05 11:56 UTC, merged

2017-05-05 12:17 UTC, alarcher commented
@dsendkowski Thanks!

2017-05-05 13:04 UTC, dsendkowski commented
@alarcher Thank you.

2017-05-30 19:19 UTC, alarcher commented
@dsendkowski There is a new version out :)

2017-05-30 20:13 UTC, dsendkowski commented
Nice :)