Pull mate 1.16.x updates from kenmays/oi-userland
OpenIndiana/oi-userland pull request #3063
Opened 2017-05-08 15:48 UTC by kenmays

Pull 2017-05-08

2017-05-09 00:53 UTC, alarcher commented
Caja 1.16.5 requires mate-desktop-2.0 >= 1.16.2 so the build will fail on the server if the PR is merged.
It should be put in a subsequent PR.

2017-05-09 12:06 UTC, kenmays commented
Mate-desktop is defined for version 1.16.2.https://github.com/kenmays/oi-userland/blob/oi/hipster/components/desktop/mate/mate-desktop/Makefile


On Monday, May 8, 2017, 5:53:44 PM PDT, Aurélien Larcher <notifications@github.com> wrote:
Caja 1.16.5 requires mate-desktop-2.0 >= 1.16.2 so the build will fail on the server if the PR is merged.
It should be put in a subsequent PR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-05-09 13:19 UTC, alarcher commented
Exactly, as soon as the PR is merged caja will be built in an environment where mate-desktop 1.16.1 only is installed so it will fail:
- a first PR should include mate-desktop 1.16.2 so that it is built then installed on the build server,
- then a second PR will update caja which can now be built in the environment containing newly installed mate-desktop.
Keep it mind that the components are only installed after all of them have been published.
Thank you :)

2017-05-09 14:49 UTC, alarcher requested changes
Build done and tested.
Merge commit should be removed and Caja should pe put in a second PR.

2017-05-10 04:11 UTC, kenmays commented
Closing this pull request for merge corrections.

2017-05-10 04:13 UTC, alarcher commented
@kenmays Keep it open, it is fine.

2017-05-10 04:16 UTC, alarcher commented
@kenmays Do like this:
git checkout oi/hipster
git checkout -b caja
to keep your caja commit in a branch.

git checkout oi/hipster
git rebase -i HEAD~9

then remove the lines with the merge commit and caja

git push -f 

to push again you branch, the PR will be updated automatically.

2017-05-12 05:53 UTC, pyhalov commented on components/desktop/mate/mate-terminal/Makefile
>  COMPONENT_REVISION=	1
Please, remove COMPONENT_REVISION while updating COMPONENT_VERSION

2017-05-12 06:01 UTC, pyhalov commented on components/desktop/mate/mate-control-center/Makefile
> +COMPONENT_VERSION=	1.16.1
COMPONENT_ARCHIVE_HASH is not updated

2017-05-12 06:34 UTC, pyhalov commented on components/desktop/mate/mate-themes/Makefile
>  COMPONENT_ARCHIVE_URL=	http://pub.mate-desktop.org/releases/themes/3.20/$(COMPONENT_ARCHIVE)
Doesn't publish:
`` Couldn't find 'usr/share/themes/Menta/gtk-3.0/assets/slider-hover.png' in any of the specified search directories:``
and so on. Have you updated manifests and sample-manifests?

2017-05-15 14:09 UTC, kenmays commented
Latest updates are at MATE 1.18 (2017-05-15). The older ones are updated for the latest MATE 1.16 updates to fix previous pull request by Alex.

2017-05-16 20:50 UTC, alarcher commented
@kenmays A few missing build dependencies were fixed in this branch https://github.com/OpenIndiana/oi-userland/pull/3014 It would be good to add them.

2017-05-17 21:30 UTC, alarcher commented
@kenmays @pyhalov @xen0l @Toasterson Do we want 64bit builds only?

2017-05-18 04:01 UTC, kenmays commented
MATE 1.18.x 64-bit eventually..

2017-05-18 07:24 UTC, pyhalov commented
For binaries - likely

2017-05-18 16:07 UTC, Toasterson commented
I would also say for binaries yes and for libs keep 32bit for now.

2017-05-20 11:23 UTC, kenmays commented
I converted MATE 1.18 entirely over to 64-bit, You can review from this point.

2017-05-31 14:10 UTC, alarcher commented
@kenmays @pyhalov Thank you for your work on MATE! It looks all good!

2017-05-31 14:42 UTC, pyhalov commented
Superseded by #3177 , #3178, #3179 , #3181, #3182

2017-05-31 14:42 UTC, closed without merging