Add Openbox window manager
OpenIndiana/oi-userland pull request #3064
Opened 2017-05-08 16:38 UTC by dsendkowski

2017-05-09 15:35 UTC, alarcher requested changes
Tested on my machine.
You need to fix the 0555 mode but otherwise good.
Thank you.

2017-05-09 15:35 UTC, alarcher commented on components/desktop/openbox/openbox.p5m
> +file path=usr/libexec/openbox-autostart
Executables in /usr/libexec need "mode=0555" added at the end of the line.

2017-05-09 15:45 UTC, dsendkowski commented on components/desktop/openbox/openbox.p5m
> +file path=usr/libexec/openbox-autostart
Like this?:
```
file path=usr/libexec/openbox-autostart mode=0555
file path=usr/libexec/openbox-xdg-autostart mode=0555
```

2017-05-09 15:49 UTC, alarcher commented on components/desktop/openbox/openbox.p5m
> +file path=usr/libexec/openbox-autostart
Yes!

2017-05-09 15:52 UTC, alarcher commented on components/desktop/openbox/openbox.p5m
> +file path=usr/libexec/openbox-autostart
For reference, default transforms set the modes at https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/transforms/defaults#L105

2017-05-09 17:02 UTC, dsendkowski commented on components/desktop/openbox/openbox.p5m
> +file path=usr/libexec/openbox-autostart
I added missing `python` and `python-xdg` dependencies, which emerged after specifying python version for `openbox-xdg-autostart`.

2017-05-09 21:32 UTC, xen0l approved these changes

2017-05-09 21:40 UTC, alarcher approved these changes

2017-05-09 21:42 UTC, merged

2017-06-07 18:44 UTC, alarcher commented
@dsendkowski I just noticed that files were delivered in /usr/libexec. We do not use this folder: depending on the type of file either we put the binaries in /usr/bin or we put libraries in /usr/lib/$component/.

2017-06-07 19:04 UTC, pyhalov commented
Usually we put them in /usr/lib. /usr/lib/$component was usually used for mate to avoid intersections with gnome.

2017-06-07 19:05 UTC, alarcher commented
In this particular case libexecdir may be set to /usr/bin to be consistent with other components;
```
file path=usr/libexec/openbox-autostart
file path=usr/libexec/openbox-xdg-autostart
```

2017-06-07 20:19 UTC, dsendkowski commented
OK, but first I'll check whether moving these files requires any additional changes.

2017-06-07 20:21 UTC, alarcher commented
Sure. This is not a priority, no rush. It would just be nice to fix it at some point.