Add pslib
OpenIndiana/oi-userland pull request #3091
Opened 2017-05-18 18:54 UTC by dsendkowski

2017-05-18 20:55 UTC, xen0l requested changes

2017-05-18 20:55 UTC, xen0l commented on components/print/pslib/Makefile
> +REQUIRED_PACKAGES += image/library/libjpeg6
This seems to be an error, There should be only one libjpeg implementation as a dependency. Also the package seems to be badly linked:
<pre>
xenol@external lib (pslib) % ldd libps.so 
        libpng16.so.16 =>        /usr/lib/libpng16.so.16
        libjpeg.so.62 =>         /usr/lib/libjpeg.so.62
        libtiff.so.5 =>  /usr/lib/libtiff.so.5
        libc.so.1 =>     /lib/libc.so.1
        libz.so.1 =>     /usr/lib/libz.so.1
        libm.so.2 =>     /lib/libm.so.2
        liblzma.so.5 =>  /usr/lib/liblzma.so.5
        libjpeg.so.8 =>  /usr/lib/libjpeg8-turbo/lib/libjpeg.so.8
        libmd.so.1 =>    /lib/libmd.so.1
        libpthread.so.1 =>       /lib/libpthread.so.1
</pre>

Preferably, link to libjpeg-turbo. @pyhalov / @alarcher anything else?

2017-05-18 20:55 UTC, xen0l commented on components/print/pslib/pslib.p5m
> +file path=usr/include/libps/pslib-mp.h
Are headers the same for 32-bit and 64-bit versions?

2017-05-19 07:32 UTC, dsendkowski commented on components/print/pslib/Makefile
> +REQUIRED_PACKAGES += image/library/libjpeg6
I did add these jpeg8-turbo options and 64bits library is linked correctly:
```
ldd build/prototype/i386/usr/lib/amd64/libps.so
	libpng16.so.16 =>	 /usr/lib/64/libpng16.so.16
	libjpeg.so.8 =>	 /usr/lib/libjpeg8-turbo/lib/amd64/libjpeg.so.8
	libtiff.so.5 =>	 /usr/lib/64/libtiff.so.5
	libc.so.1 =>	 /lib/64/libc.so.1
	libz.so.1 =>	 /usr/lib/64/libz.so.1
	libm.so.2 =>	 /lib/64/libm.so.2
	liblzma.so.5 =>	 /usr/lib/64/liblzma.so.5
	libpthread.so.1 =>	 /lib/64/libpthread.so.1
```
however 32bits is not:
```
ldd build/prototype/i386/usr/lib/libps.so
	libpng16.so.16 =>	 /usr/lib/libpng16.so.16
	libjpeg.so.62 =>	 /usr/lib/libjpeg.so.62
	libtiff.so.5 =>	 /usr/lib/libtiff.so.5
	libc.so.1 =>	 /lib/libc.so.1
	libz.so.1 =>	 /usr/lib/libz.so.1
	libm.so.2 =>	 /lib/libm.so.2
	liblzma.so.5 =>	 /usr/lib/liblzma.so.5
	libjpeg.so.8 =>	 /usr/lib/libjpeg8-turbo/lib/libjpeg.so.8
	libpthread.so.1 =>	 /lib/libpthread.so.1
```
Are there any additional options I should add?

2017-05-19 07:34 UTC, dsendkowski commented on components/print/pslib/pslib.p5m
> +file path=usr/include/libps/pslib-mp.h
Yes, they are.

2017-05-19 08:50 UTC, pyhalov commented on components/print/pslib/Makefile
> +REQUIRED_PACKAGES += image/library/libjpeg6
Can't say without looking at component's Makefiles

2017-05-19 10:08 UTC, dsendkowski commented on components/print/pslib/Makefile
> +REQUIRED_PACKAGES += image/library/libjpeg6
Ok, I think I found what causes this issue. Can I patch `configure` only or I should patch rather `configure.in`?

2017-05-19 10:56 UTC, pyhalov commented on components/print/pslib/Makefile
> +REQUIRED_PACKAGES += image/library/libjpeg6
Better patch configure.ac or configure.in

2017-05-19 12:03 UTC, dsendkowski commented
I'm afraid I need to close this PR. There are too many patches required in the source code itself so that it can be used in 64bits.

2017-05-19 12:03 UTC, closed without merging