Bump libtool to 2.4.6
OpenIndiana/oi-userland pull request #3233
Opened 2017-06-05 19:21 UTC by alarcher

Let us test more on our systems before merging.

2017-06-13 10:04 UTC, pyhalov commented
Have you checked a significant number of components, using libtoolize/autoreconf?

2017-06-13 10:06 UTC, alarcher commented
Basically everything I have built in the past 8 days.

2017-06-13 12:28 UTC, pyhalov commented on components/developer/libtool/Makefile
> +#COMPONENT_PREP_ACTION = (cd $(@D) ; ./bootstrap --force)
Why did you comment it out (Look at https://github.com/oracle/solaris-userland/blob/master/components/libtool/Makefile#L46  )?

2017-06-13 12:29 UTC, pyhalov commented on components/developer/libtool/Makefile
> +REQUIRED_PACKAGES += compatibility/ucb
Why do we need it?

2017-06-13 12:33 UTC, alarcher commented on components/developer/libtool/Makefile
> +REQUIRED_PACKAGES += compatibility/ucb
Because the original solairs manifest has an explicit dependency on it?

2017-06-13 12:37 UTC, pyhalov commented on components/developer/libtool/Makefile
> +REQUIRED_PACKAGES += compatibility/ucb
Preciesely.

2017-06-13 12:42 UTC, alarcher commented on components/developer/libtool/Makefile
> +#COMPONENT_PREP_ACTION = (cd $(@D) ; ./bootstrap --force)
I remember using it and concluding that it is not needed. I will double check.

2017-06-19 13:24 UTC, pyhalov commented on components/developer/libtool/Makefile
> +#COMPONENT_PREP_ACTION = (cd $(@D) ; ./bootstrap --force)
ping

2017-06-19 22:42 UTC, alarcher commented
Updated.

2017-06-20 09:04 UTC, pyhalov requested changes

2017-06-20 09:04 UTC, pyhalov commented on components/developer/libtool/Makefile
> +COMPONENT_PREP_ACTION = (cd $(@D) ; ./bootstrap --force)
please, add --no-git to avoid fetching sources from git://git.sv.gnu.org in build time

2017-06-20 09:04 UTC, pyhalov commented on components/developer/libtool/Makefile
> +COMPONENT_PREP_ACTION = (cd $(@D) ; ./bootstrap --force)
prep step fails if you avoid touching  $(SOURCE_DIR)/README-release  (look at solaris-userland)

2017-06-20 16:17 UTC, alarcher commented
Updated.

2017-06-20 19:55 UTC, pyhalov commented on components/developer/libtool/libtool.p5m
> +depend fmri=__TBD pkg.debug.depend.file=usr/bin/echo type=require
This one is exactly not needed (seems as well as usr/ucb/echo). Now we see in libtoolize:
: ${ECHO="printf %s\n"}

2017-06-20 20:02 UTC, alarcher commented
Updated.

2017-06-20 20:04 UTC, pyhalov approved these changes

2017-06-20 20:04 UTC, merged