cluster-glue: compile as 64-bit
OpenIndiana/oi-userland pull request #3520
Opened 2017-09-26 19:04 UTC by grueni

2017-09-26 19:13 UTC, AndWac commented on components/cluster/cluster-glue/Makefile
You need to set COMPONENT_REVISION

2017-09-26 19:57 UTC, xen0l commented
Please, set CONFIGURE_BINDIR.64 like [here](https://github.com/OpenIndiana/oi-userland/blob/b6ca80a20fb2f5e4e777be54f0bdf34372fde345/components/shell/dash/Makefile#L41) and don't forget to bump COMPONENT_REVISION if COMPONENT_VERSION does not change.

2017-09-26 19:58 UTC, xen0l requested changes
Please, set CONFIGURE_BINDIR.64 like [here](https://github.com/OpenIndiana/oi-userland/blob/b6ca80a20fb2f5e4e777be54f0bdf34372fde345/components/shell/dash/Makefile#L41) and don't forget to bump COMPONENT_REVISION if COMPONENT_VERSION does not change.

2017-10-14 11:38 UTC, pyhalov commented
Superseeded by https://github.com/OpenIndiana/oi-userland/pull/3560

2017-10-14 11:39 UTC, closed without merging