corosync: compile as 64-bit
OpenIndiana/oi-userland pull request #3521
Opened 2017-09-26 19:05 UTC by grueni

2017-09-26 19:08 UTC, AndWac commented on components/cluster/corosync/Makefile
>  COMPONENT_VERSION= 2.4.2
If you don't change COMPONENT_VERSION you should add (or increment if already there) COMPONENT_REVISION.

2017-09-26 19:57 UTC, xen0l requested changes
Please, set CONFIGURE_BINDIR.64 like [here](https://github.com/OpenIndiana/oi-userland/blob/b6ca80a20fb2f5e4e777be54f0bdf34372fde345/components/shell/dash/Makefile#L41) and don't forget to bump COMPONENT_REVISION if COMPONENT_VERSION does not change.

2017-10-14 08:59 UTC, xen0l approved these changes

2017-10-18 20:46 UTC, xen0l approved these changes

2017-10-18 20:46 UTC, merged