libmng: Move to library section
OpenIndiana/oi-userland pull request #4087
Opened 2018-04-16 04:32 UTC by hliebel

2018-04-17 11:01 UTC, alarcher requested changes

2018-04-17 11:01 UTC, alarcher commented on components/library/libmng/manifests/sample-manifest.p5m
> +# Copyright 2017 <contributor>
Do not commit changes to this file since only the date changed.

2018-04-17 11:01 UTC, alarcher commented on components/library/libmng/Makefile
> +COMPONENT_LICENSE_FILE=	$(COMPONENT_NAME).license
Remove the COMPONENT_LICENSE_FILE line.

2018-04-17 14:17 UTC, hliebel commented
Force pushed requested changes.

2018-04-19 06:22 UTC, pyhalov commented on components/library/libmng/libmng.p5m
> +file Solaris/libmng.pc path=usr/lib/pkgconfig/libmng.pc
please, put hand-crafted "file" contents section before auto-generated one. https://wiki.openindiana.org/oi/oi-userland+-+best+practices, point 10.

2018-05-02 17:19 UTC, alarcher approved these changes

2018-05-02 17:19 UTC, merged