chromium-bsu: Add new package
OpenIndiana/oi-userland pull request #4103
Opened 2018-04-18 14:29 UTC by hliebel

Depends on proposed packages 'freealut' and 'ftgl'

2018-04-19 06:35 UTC, pyhalov commented on components/games/chromium-bsu/Makefile
> +REQUIRED_PACKAGES += text/gnu-gettext
Consider adding standard '# Build dependencies' comment above this line

2018-05-02 17:52 UTC, alarcher requested changes

2018-05-02 17:52 UTC, alarcher commented on components/games/chromium-bsu/Makefile
> +REQUIRED_PACKAGES += system/library/g++-6-runtime
Can you use $(GCC_RUNTIME_PKG) and $(GXX_RUNTIME_PKG) ?

2018-08-21 10:34 UTC, hliebel commented
Hi. I rebased and force pushed this one with the requested changes.

2019-07-20 06:00 UTC, merged