augeas: bump to 1.10.1
OpenIndiana/oi-userland pull request #4130
Opened 2018-04-30 17:07 UTC by grueni

PKG.NAME             ACTION.RAW
library/ruby/augeas  depend fmri=pkg:/library/augeas-libs@1.9.0-2017.1.0.0 type=require
compiles without problems.

2018-05-02 17:49 UTC, alarcher requested changes

2018-05-02 17:49 UTC, alarcher commented on components/sysutils/augeas/Makefile
> +REQUIRED_PACKAGES += system/library/gcc-6-runtime
Please use $(GCC_RUNTIME_PKG)

2018-05-03 15:11 UTC, grueni commented
is this sufficient
REQUIRED_PACKAGES += $(GCC_RUNTIME_PKG)
or should I do anything else?

2018-05-03 16:38 UTC, alarcher approved these changes

2018-05-03 16:38 UTC, merged

2018-05-03 16:38 UTC, alarcher commented
I hate the github interface on the phone... squash and merge does not work...