xmlxec: add 1.2.28
OpenIndiana/oi-userland pull request #5253
Opened 2019-08-22 08:39 UTC by grueni

dependency of lasso

2019-08-23 19:59 UTC, Mno-hime commented on components/library/xmlsec/Makefile
> +BITS=64
We go with
```suggestion
BUILD_BITS=64
```
before `include ../../../make-rules/shared-macros.mk`.

2019-08-23 19:59 UTC, Mno-hime commented on components/library/xmlsec/Makefile
> +PATH=$(PATH.gnu)
For consistency with the rest of components put it after the `COMPONENTS_` block.

2019-08-23 19:59 UTC, Mno-hime commented on components/library/xmlsec/manifests/sample-manifest.p5m
> +file path=usr/lib/$(MACH64)/libxmlsec1-gcrypt.a
Do we want `ar` archives? If not `--enable-static=no` should remove them.

2019-08-23 20:15 UTC, alarcher requested changes

2019-08-23 20:15 UTC, alarcher commented on components/library/xmlsec/Makefile
> +CONFIGURE_OPTIONS +=	NSS_LIBS="-L/usr/lib/64 -R/usr/lib/64"
Is it really necessary?

2019-08-23 20:15 UTC, alarcher commented on components/library/xmlsec/Makefile
> +BITS=64
Should be BUILD_BITS=64

2019-08-23 20:15 UTC, alarcher commented on components/library/xmlsec/Makefile
> +CONFIGURE_OPTIONS += --bindir=$(USRBINDIR)
Should be automatic with BUILD_BITS=64 since PREFERRED_BITS=64 is applied, see shared-macros.mk.

2019-08-24 14:03 UTC, grueni commented
@Mno-hime, @alarcher Thanks for the hints. Lession learned.

2019-08-24 20:05 UTC, Mno-hime approved these changes

2019-08-25 11:43 UTC, alarcher approved these changes

2019-08-25 11:44 UTC, merged