Update to tmux-3.0a
OpenIndiana/oi-userland pull request #5411
Opened 2019-12-09 14:15 UTC by rapenne-s

2019-12-09 19:32 UTC, AndWac commented on components/sysutils/tmux/Makefile
>  COMPONENT_FMRI=		terminal/tmux
There is a special treatment for version numbers pkg cannot cope with:
COMPONENT_VERSION=   3.0a
IPS_COMPONENT_VERSION= 3.0.1
(See openssl for another example)

2019-12-09 19:33 UTC, AndWac commented on components/sysutils/tmux/Makefile
>  COMPONENT_LICENSE_FILE=	COPYING
Remove the trailing "a" when you changed the COMPONENT_VERSION

2019-12-09 19:45 UTC, AndWac requested changes

2019-12-09 19:45 UTC, AndWac commented on components/sysutils/tmux/Makefile
Please try to adapt to the new style (see runtime/node12 as an example):
Insert

BUILD_BITS=    64

before importing shared-macros.mk

Later replace
include $(WS_MAKE_RULES)/prep.mk
include $(WS_MAKE_RULES)/configure.mk
include $(WS_MAKE_RULES)/ips.mk

with
TEST_TARGET=    $(NO_TESTS)
include $(WS_MAKE_RULES)/common.mk

and remove

build:		$(BUILD_64)
install:	$(INSTALL_64)
test:		$(NO_TESTS)

2019-12-10 16:38 UTC, AndWac commented
Ok, final question: Did you check whether the sample-manifest changed? 
gmake sample-manifest will create a new one, so you can check whether there are changes.
If so, you will need to adapt the .p5m file accordingly.
When everything is done please squash the commits into a single one.

2019-12-10 17:03 UTC, rapenne-s commented
I did check for changes in the manifest before and there are none

2019-12-10 17:36 UTC, AndWac commented
This is good, but you should check again after the switch to the new style. There might be some incompabilities. I don't expect any here, though, because the Makefile is quite simple.

2019-12-10 18:07 UTC, rapenne-s commented
I did compare the manifest after the new syntax change of course (and building has been tried too).

2019-12-10 18:42 UTC, merged

2019-12-11 08:07 UTC, Mno-hime commented on components/sysutils/tmux/Makefile
> +#CONFIGURE_BINDIR.64 = $(CONFIGURE_BINDIR.32)
I think this should have been dropped when moved to the `BUILD_BITS=64` style.

2019-12-11 19:54 UTC, AndWac commented
Am 11.12.19 um 09:07 schrieb Michal Nowak:
>
> *@Mno-hime* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In components/sysutils/tmux/Makefile
> <https://github.com/OpenIndiana/oi-userland/pull/5411#discussion_r356449427>:
>
> >
>   CFLAGS +=	-I/usr/include/ncurses
>
> -CONFIGURE_BINDIR.64 = $(CONFIGURE_BINDIR.32)
> +#CONFIGURE_BINDIR.64 = $(CONFIGURE_BINDIR.32)
>
> I think this should have been dropped when moved to the
> |BUILD_BITS=64| style.
>
Yes, you are right. Sorry, I missed it.

2019-12-12 07:36 UTC, Mno-hime commented
> Yes, you are right. Sorry, I missed it.

No problem, we will fix it when tmux gets a new release. Thanks for working on having this merged.