userland: bass-o-matic recurses in illumos-gate and openssl-0.9.8 directories
OpenIndiana/oi-userland pull request #5842
Opened 2020-06-02 15:35 UTC by alarcher

If there is not *.p5m file then bass-o-matic recurses in the directory to find manifests.
It takes quite a long time in illumos-gate source and build trees.

2020-06-03 18:23 UTC, AndWac approved these changes

2020-06-04 20:36 UTC, pyhalov commented
This will likely make both components real components and oi-userland build will build them. And we don't wont this on the build server.

2020-06-04 20:38 UTC, pyhalov requested changes
This will make full oi-userland build include these components, but we don't want this.

2020-06-04 21:17 UTC, alarcher commented
> This will make full oi-userland build include these components, but we don't want this.

OK thanks I missed that :(
Then we should add them to an exclusion list because the rule for finding a component path is to recurse until a .p5m is found.
Otherwise I'll leave it until we move forward on the changes to bass-o-matic.

2020-06-05 20:53 UTC, pyhalov commented
I'm fine with adding them to exclusion list. Check that illumos-gate build job is not affected.

2020-06-06 19:19 UTC, alarcher commented
> I'm fine with adding them to exclusion list. Check that illumos-gate build job is not affected.

OK. I added them to components.ignore to make sure they do not appear in COMPONENT_DIRS.
They both publish correctly, I will check the Jenkins build job in my build zone.

2020-06-06 21:24 UTC, xen0l approved these changes

2020-06-06 21:40 UTC, alarcher commented
Tested Jenkins build job in the gcc-10 zone.

2020-06-06 21:41 UTC, merged