tor: Update to 0.4.3.5
OpenIndiana/oi-userland pull request #5848
Opened 2020-06-10 19:10 UTC by svschmel

Tor v0.4.1.x reached its end of life on 2020-05-20.
https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases

Update to version 0.4.3.5.

```
==============================================
Testsuite summary for tor 0.4.3.5
==============================================
# TOTAL: 24
# PASS:  21
# SKIP:  3
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
==============================================
```

This version works fine:
https://metrics.torproject.org/rs.html#details/AD0FCFD83EA4899DB34735E599701592DEA13690

2020-06-10 20:47 UTC, alarcher requested changes
Excellent update thank you :)
Just a small favour, could you run 'gmake test'?
After that you need to copy 'build/test/amd64/results-64.snapshot' to 'test/results-64.master then commit the changes.
I'll merge after that :)

2020-06-10 20:47 UTC, alarcher commented on components/network/tor/Makefile
>  COMPONENT_REVISION=	1
You forgot to remove the COMPONENT_REVISION variable.

2020-06-11 09:40 UTC, svschmel commented
Hello,

- COMPONENT_REVISION variable => removed 
- copy 'build/test/amd64/results-64.snapshot' to 'test/results-64.master => done
- commit => done

I hope this is it :)

Regards

2020-06-11 09:44 UTC, alarcher commented
> Hello,
> 
>     * COMPONENT_REVISION variable => removed
> 
>     * copy 'build/test/amd64/results-64.snapshot' to 'test/results-64.master => done
> 
>     * commit => done
> 
> 
> I hope this is it :)
> 
> Regards

Great! thank you :)

2020-06-11 09:47 UTC, alarcher approved these changes
Squashed commits, all good!

2020-06-11 09:47 UTC, merged