dmenu: update to 4.9 and drop 32-bit
OpenIndiana/oi-userland pull request #5992
Opened 2020-08-09 09:04 UTC by AndWac

2020-08-09 12:54 UTC, pyhalov requested changes

2020-08-09 12:54 UTC, pyhalov commented on components/desktop/dmenu/patches/01-config-mk.patch
> ++CC = gcc
Should we just remove `CC = cc` or set to `CC ?= gcc` to use oi-userland gcc, not any?

2020-08-09 13:05 UTC, AndWac commented
Ok, I removed it.

2020-08-12 14:54 UTC, AndWac commented
Are you fine with the change?

2020-08-13 04:11 UTC, pyhalov commented
Seems to be fine

2020-08-13 04:12 UTC, pyhalov approved these changes

2020-08-13 04:39 UTC, merged