add samurai package.
OpenIndiana/oi-userland pull request #9187
Opened 2022-09-07 18:30 UTC by vtorri

samurai is a ninja-compatible build tool written in C

2022-09-07 19:53 UTC, Toasterson requested changes
Please fix your autodetection of paths they must be relative to the prototype directory.

2022-09-07 19:53 UTC, Toasterson commented on components/developer/samurai/manifests/sample-manifest.p5m
> +file path=export/home/vtorri/gitroot/oi-userland/components/developer/samurai/build/prototype/$(MACH)/usr/bin/samu
This is wrong it should be `file path=usr/bin/samu` the autodetection looks broken on your system

2022-09-08 14:09 UTC, Toasterson requested changes
paths must be relative. Please use `gmake sample-manifest` as example.

2022-09-09 11:06 UTC, alarcher commented on components/developer/samurai/Makefile
> +COMPONENT_BUILD_ENV += CC="/usr/bin/gcc"
You could event just pass CC=$(CC) to use the compiler toolchain selected with GCC_VERSION.

2022-09-09 12:10 UTC, vtorri commented
@alarcher thank you, i'll redo it with @Toasterson's patch:
https://gist.github.com/Toasterson/d937cb678fccb2dabae8cb5de9450a40

2022-09-09 15:28 UTC, vtorri commented
I've updated my gist:

https://gist.github.com/vtorri/d1d78062795832403e334a132bad702f

I'll try it this evening or tomorrow

2022-09-09 18:51 UTC, vtorri commented
will do another PR, closing this one

2022-09-09 18:51 UTC, closed without merging