rust - update to version 1.64.0
OpenIndiana/oi-userland pull request #9375
Opened 2022-09-27 19:58 UTC by fritzkink

currently there is no system/library/g++-4-runtime installed only two links are needed
to build the package:

      `ln -s $(GCC_LIBDIR)/libgcc_s.so.1 /usr/lib/$(MACH64)/libgcc_s.so.1`
      `ln -s $(GCC_LIBDIR)/liblibssp.so.0 /usr/lib/$(MACH64)/libssp.so.0`

 another idea could be to usr LD_LIBRARY_PATH only caveat it starts building included
 llvm and fails (maybe someone can chime in)

      `export LD_LIBRARY_PATH=$(GCC_LIBDIR)`

 Also some other package can provide this two links (which one?)
 Basically it proves that the very old gcc is not needed as also mentioned by Joshua M. Clulow

2022-10-09 11:06 UTC, AndWac commented
This doesn't build here:

   Compiling toml v0.5.9
    Finished dev [unoptimized] target(s) in 41.40s
Building stage0 std artifacts (x86_64-unknown-illumos -> x86_64-unknown-illumos)
error: unknown `-Z` flag specified: check-cfg
Build completed unsuccessfully in 0:00:42
make[1]: *** [Makefile:54: install] Error 1
make[1]: Leaving directory '/export2/home/andreas/oi-userland/components/developer/rust/build/amd64'
gmake: *** [/export2/home/andreas/oi-userland/make-rules/configure.mk:183: /export2/home/andreas/oi-userland/components/developer/rust/build/amd64/.installed] Error 2

2022-10-09 18:05 UTC, fritzkink commented
Hmm, I just run the build target again on my system  without any problem. I also don't see where a -z flag is used in the Makefile.

2022-10-15 13:59 UTC, AndWac commented
I have checked this on my 2nd build system with the same error. Are you sure your system is up-to-date and clean? I cannot merge this because it is most likely that this will also fail on the official build system.

2022-10-16 18:55 UTC, fritzkink commented
It seems that all settings for the COMPONENT_BUILD_ENV from the Makefile are ignored. Did something change here? Basically my environment is up to date.

2022-10-22 07:34 UTC, AndWac commented
@mtelka: Do you have an idea? It would break many package builds if that is generally true.

2022-10-22 08:41 UTC, mtelka commented
> It seems that all settings for the COMPONENT_BUILD_ENV from the Makefile are ignored.

@fritzkink: Why do you think this happens?  Any steps and/or logs supporting your claim?  Thanks.

2022-10-22 09:37 UTC, mtelka commented
I just tried to rebase [fritzkink:rust](https://github.com/fritzkink/oi-userland/tree/rust) on top of current git head (with all packages up-to-date) and then run `gmake sample-manifest` and this is the result (the full path was manually replaced by `XXXYYYXXX` in the output):

```
make[1]: Entering directory 'XXXYYYXXX/components/developer/rust/build/amd64'
make[1]: Nothing to be done for 'x.py'.
Building rustbuild
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
failed to run: XXXYYYXXX/components/developer/rust/build/amd64/bin/cargo build --manifest-path XXXYYYXXX/components/developer/rust/rustc-1.64.0-src/src/bootstrap/Cargo.toml --frozen
Build completed unsuccessfully in 0:00:00
make[1]: *** [Makefile:54: install] Error 1
```

To make it short: it does not build.  Why?  I do not know and I'd prefer to not go to the rust hell yet if possible.  For now Python hell is enough for me. :-)

2022-10-22 10:04 UTC, mtelka requested changes

2022-10-22 10:04 UTC, mtelka commented on components/developer/rust/Makefile
>  COMPONENT_BUILD_ENV+=	CARGO_HOME=$(CARGO_HOME)
There are some strange things in the `Makefile`.  Something is added to the `COMPONENT_BUILD_ENV` here...

2022-10-22 10:04 UTC, mtelka commented on components/developer/rust/Makefile
>  COMPONENT_BUILD_ENV =
...and then the `COMPONENT_BUILD_ENV` is cleaned here.

Definitely, this `Makefile` needs some love.

2022-12-30 23:27 UTC, fritzkink commented
superseeded by a newer pull request

2022-12-30 23:27 UTC, closed without merging